### ISSUE TITLE
Not possible to replicate results of exp cones

### ISSUE THREAD

**Issue by bernalde** [chriscoey/PajaritoSupplement#1]
Hi!
While trying to replicate the results of your repository I found that, given that the current version of MOSEK 8.1.0.53, I had to get an alpha version of MOSEK 9. Following your indications, I downloaded the files but the library libmosekscopt9_0.so was missing, making Mosek impossible to build in Julia and therefore failing for all exponential cones MICP (rsyn* and syn* instances).
Shall we just wait for the release of a stable version of Mosek 9? Where can I get that binary file otherwise?

**Comment by chriscoey** [comment]
Hi @bernalde, sorry about the delay (I'm on break in Thailand). This supplement is for a paper that we have not released yet (but we will in the next few weeks), on the conic version of Pajarito (as opposed to the old NLP version, which was tested here https://github.com/mlubin/MICPExperiments). 

Yes, the tests in this repo require Mosek 9, and I think you will need to wait for it to be released (unclear when that will be). We had to get a special licence and download link from Mosek for the 9-alpha version just for the purpose of our computational experiments.

**Comment by bernalde** [comment]
No problem! I hope you enjoyed your vacations.
I guess that I will have to wait until the official release of Mosek 9.
Thanks.

**Comment by chriscoey** [comment]
If you like, you could manually replace mosek with ecos solver (open source, easy to install, just look at ecos.jl), which handles Second order and Exp cones, but not Psd cones. This would allow you to run the syn and rsyn instances at least.
